### ISSUE TITLE
The phpactor binary fails to install due to wrong URL to upstream project

### ISSUE THREAD

**Issue by vendion** [gbprod/phpactor.nvim#1]
After adding `phpactor.nvim` to my neovim config and installing it I kept getting access errors from when when it would try and clone the upstream repo. Changing the URL in _lua/phpactor/handler/update.lua_ fixed the issue.

```diff
diff --git a/lua/phpactor/handler/update.lua b/lua/phpactor/handler/update.lua
index 869b035..167d57b 100644
--- a/lua/phpactor/handler/update.lua
+++ b/lua/phpactor/handler/update.lua
@@ -18,7 +18,7 @@ return function()
trace = vim.fn.system({
config.options.install.git_bin,
"clone",
-      "git@github.com:phpactor/phpactor",
+      "https://github.com/phpactor/phpactor.git",
phpactor_path:absolute(),
})
```

After doing that I was able to run `:PhpActor update` and get everything installed.

**Comment by gbprod** [comment]
I see, I can add an option for that.
I don't have my computer this week, I'll implement this next week.

Thanks for reporting this issue.

**Comment by gbprod** [comment]
Fixed :)
