### ISSUE TITLE
How to use with Telescope?

### ISSUE THREAD

**Issue by arturolinares** [gbprod/phpactor.nvim#22]
Would it be possible to use this fantastic plugin with telescope?

I would like to see a telescope fuzzy finder for the override method list from the context_menu. Is this possible?

In fact, it would be nice to see in telescope all the option lists that this plugin displays, not just the override method list :)

**Comment by gbprod** [comment]
Hey!
This plugin uses native "modern" ui methods of neovim like `vim.ui.select` or `vim.ui.input`. You can override these methods to use telescope with plugins like https://github.com/stevearc/dressing.nvim or https://github.com/nvim-telescope/telescope-ui-select.nvim :)

**Comment by arturolinares** [comment]
Thank you!
