### ISSUE TITLE
phpactor handler update not found

### ISSUE THREAD

**Issue by tonmoy998** [gbprod/phpactor.nvim#24]
Failed to load `plugins.custom`

/home/tonmoy/.config/nvim/lua/plugins/custom.lua:4: module 'phpactor.handler.update' not found:
	no field package.preload['phpactor.handler.update']
cache_loader: module phpactor.handler.update not found
cache_loader_lib: module phpactor.handler.update not found
	no file './phpactor/handler/update.lua'
	no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1/phpactor/handler/update.lua'
	no file '/usr/local/share/lua/5.1/phpactor/handler/update.lua'
	no file '/usr/local/share/lua/5.1/phpactor/handler/update/init.lua'
	no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/phpactor/handler/update.lua'
	no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/phpactor/handler/update/init.lua'
	no file './phpactor/handler/update.so'
	no file '/usr/local/lib/lua/5.1/phpactor/handler/update.so'
	no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/phpactor/handler/update.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './phpactor.so'
	no file '/usr/local/lib/lua/5.1/phpactor.so'
	no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/phpactor.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

**Comment by gbprod** [comment]
Can you share your config ?

**Comment by tonmoy998** [comment]
I am using lazyvim framework.

**Comment by gbprod** [comment]
Ok, so it should looks like :

```lua
{
    "gbprod/phpactor.nvim",
    build = function()
      require("phpactor.handler.update")()
    end,
    opts = {},
  },
```

**Comment by tonmoy998** [comment]
Thank you worked
