### ISSUE TITLE
how to install it using Lazy?

### ISSUE THREAD

**Issue by ahmedsayedabdelsalam** [gbprod/phpactor.nvim#36]

**Comment by gbprod** [comment]
you can install this plugin using lazy with this config : 

```lua
{
  {
    "gbprod/phpactor.nvim",
    build = function()
      require("phpactor.handler.update")()
    end,
    dependencies = {
      "nvim-lua/plenary.nvim", 
      "neovim/nvim-lspconfig"
    },
    opts = {},
  },
}
```

I will update the README

**Comment by ahmedsayedabdelsalam** [comment]
> you can install this plugin using lazy with this config :
> 
> ```lua
> {
>   {
>     "gbprod/phpactor.nvim",
>     build = function()
>       require("phpactor.handler.update")()
>     end,
>     dependencies = {
>       "nvim-lua/plenary.nvim", 
>       "neovim/nvim-lspconfig"
>     },
>     opts = {},
>   },
> }
> ```
> 
> I will update the README

thanks 🙏
