### ISSUE TITLE
Build failed when installing

### ISSUE THREAD

**Issue by gaizkx** [gbprod/phpactor.nvim#38]
`.../nvim/lazy/phpactor.nvim/lua/phpactor/handler/update.lua:5: attempt to index field 'install' (a nil value)`

**Comment by gbprod** [comment]
Can you share your config ?

**Comment by gaizkx** [comment]
I've just added this to Lazy.nvim plugins file:

`{
    "gbprod/phpactor.nvim",
    build = function()
      require("phpactor.handler.update")()
    end,
    dependencies = {
      "nvim-lua/plenary.nvim",
      "neovim/nvim-lspconfig"
    },
    opts = {
      -- you're options coes here
    },
  },`

**Comment by gbprod** [comment]
Maybe there is something missing in the readme, I don't have a computer to test for now but can you try with :

```lua
{ 
  "gbprod/phpactor.nvim", 
   build = function()
    require("phpactor.handler.update")() 
  end, 
  dependencies = { 
    "nvim-lua/plenary.nvim", 
    "neovim/nvim-lspconfig" 
  }, 
  opts = { 
    -- you're options coes here 
  }, 
  config = true
},
```

**Comment by gaizkx** [comment]
Sorry, it throws the same error.

**Comment by gbprod** [comment]
ok, that's strange... 
I think you should remove this for the moment and rely on the [install.check_on_startup](https://github.com/gbprod/phpactor.nvim?tab=readme-ov-file#installcheck_on_startup) option instead...

**Comment by mikedfunk** [comment]
@gaizkx try this:

```lua
{ 
  "gbprod/phpactor.nvim", 
  build = function()
    require("phpactor.config").setup({
      -- your options here
    })
    require("phpactor.handler.update")() 
  end, 
  dependencies = { 
    "nvim-lua/plenary.nvim", 
    "neovim/nvim-lspconfig" 
  }, 
  opts = { 
    -- your same options here
  }, 
},
```

Or if you use [mason.nvim](https://github.com/williamboman/mason.nvim) you can skip the build step and install it with `:Mason install phpactor`:

```lua
  {
    "gbprod/phpactor.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "neovim/nvim-lspconfig",
      {
        "williamboman/mason.nvim",
        opts_extend = { "ensure_installed" },
        opts = {
          ensure_installed = { "phpactor" },
        },
      },
    },
    opts = {
      install = {
        -- despite being under "install" this path is used when running RPC commands.
        bin = vim.fn.stdpath("data") .. "/mason/packages/phpactor/phpactor.phar",
      },
    },
  },
```

**Comment by gaizkx** [comment]
Thx @mikedfunk, that works for me!!!
