### ISSUE TITLE
Copy FCQN to clipboard 

### ISSUE THREAD

**Issue by gbprod** [gbprod/phpactor.nvim#4]
Classname also

**Comment by jsiefer** [comment]
Hi @gbprod - wondering why its not planned anymore? is there an lsp alternative for this, could not figure it out. I found the [PhpactorCopyClassName](https://github.com/phpactor/phpactor/blob/master/ftplugin/php/commands.vim#L39C82-L39C82) quite handy

**Comment by gbprod** [comment]
I don't remember why I closed this issue :sweat_smile: 
Probably because I mainly use `expand_class` 

Anyway, I've implement this here : #31 , any feedback is welcome ;)

**Comment by jsiefer** [comment]
Works like a charm, thank you @gbprod !
