### ISSUE TITLE
Default to `context_menu` instead of failing

### ISSUE THREAD

**Issue by calebdw** [gbprod/phpactor.nvim#6]
Hello! 

Instead of failing when calling `PhpActor` with no args, perhaps you could just default to the context menu?

https://github.com/gbprod/phpactor.nvim/blob/994e513f4627fd448c360391d002326f52b074bd/lua/phpactor/command.lua#L26

 Also, would it be possible to expose a lua function for the plugin as well? I prefer to use lua functions in my mappings where possible:

E.g.:

```lua
vim.keymap.set('n', '<leader>pa', require('phpactor').phpactor)
vim.keymap.set('n', '<leader>pi', function()
    require('phpactor').phpactor({ rpc = 'import_class' })
end)
```

Thanks!

**Comment by gbprod** [comment]
Yes, that's a good idea, I will work on this soon

**Comment by gbprod** [comment]
I've made something [here](#10).
You can use it now with the lua function `require('phpactor').rpc([name], [options])`.

**Comment by calebdw** [comment]
Awesome! Thanks for the quick replies!!

**Comment by calebdw** [comment]
Note that I received the following error when renaming class references:

![image](https://user-images.githubusercontent.com/4176520/221578934-53fb42f1-d641-4ce0-b31e-a98e929edd3a.png)

**Comment by gbprod** [comment]
Interesting, I create an separate issue for that.
